version: '3.4'

services:
  app:
    image: app
    env_file: .env
    build:
      context: .
      dockerfile: App/Dockerfile
    volumes:
      - $HOME/.aspnet/https:/https:ro
      - app-db:/app/db
      - app-dataprotection-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_HTTPS_PORT=8001
      - ApiService=http://api
    depends_on:
      - api
    ports: 
      - 8001:443
  api:
    image: api
    env_file: .env
    build:
      context: .
      dockerfile: Api/Dockerfile
    volumes:
      - $HOME/.aspnet/https:/https:ro
      - $HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    expose: [80]

volumes:
  app-db:
  app-dataprotection-keys: